// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<ClassifierAppMLModel.ModelInput, ClassifierAppMLModel.ModelOutput>()
    .FromFile("ClassifierAppMLModel.mlnet");

builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<ClassifierAppMLModel.ModelInput, ClassifierAppMLModel.ModelOutput> predictionEnginePool, ClassifierAppMLModel.ModelInput input) =>
        await Task.FromResult(predictionEnginePool.Predict(input)));

// Run app
app.Run();
